spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8082
          predicates :
            - Path= /wallets/**
        - id : r2
          uri: http://localhost:8081
          predicates :
            - Path= /users/**
    discovery:
      enabled: false
  application:
    name: Gateway
server:
  port: 8888